// Generated by CoffeeScript 1.10.0
(function() {
  var Admin, a,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Admin = (function() {
    function Admin(args) {
      this.btnRemoverCarona = bind(this.btnRemoverCarona, this);
      $(document).ready(function() {});
      this.visualizarRota();
      this.btnRemoverCarona();
    }

    Admin.prototype.btnRemoverCarona = function() {
      var $this;
      $this = this;
      return $(".secondary-content").on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
        return $this.removeCarona($(this).attr("data-tipo"), $(this).attr("data-id"), $(this));
      });
    };

    Admin.prototype.visualizarRota = function() {
      return $(".list-map .collection-item").on('click', function() {
        return $("#map-route iframe").attr('src', $(this).attr('href-map'));
      });
    };

    Admin.prototype.toast = function(msg) {
      return Materialize.toast(msg, 3000);
    };

    Admin.prototype.removeCarona = function(tipo, id, element) {
      var url;
      if (tipo === 'pedir') {
        url = 'excluir-pedido-carona';
      } else {
        url = 'excluir-oferta-carona';
      }
      if (confirm("Deseja realmente exlcuir?")) {
        return $.ajax({
          url: url,
          datatype: 'json',
          method: "POST",
          data: {
            id: id
          },
          success: (function(_this) {
            return function(data) {
              if (data.status) {
                _this.toast(data.msg);
                return element.parent().remove();
              } else {
                return _this.toast("Ocorreu um erro inesperado no sistema!");
              }
            };
          })(this)
        });
      }
    };

    return Admin;

  })();

  a = new Admin();

}).call(this);

//# sourceMappingURL=admin.js.map
