// Generated by CoffeeScript 1.10.0
(function() {
  var PesquisarCarona, p,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  PesquisarCarona = (function() {
    function PesquisarCarona() {
      this.eventWindow = bind(this.eventWindow, this);
      this.eventWindowResize = bind(this.eventWindowResize, this);
      this.eventWindowResize();
    }

    PesquisarCarona.prototype.eventScrollMap = function() {
      return $(window).scroll(function() {
        if ($(this).scrollTop() >= 148) {
          return $("#map-caronas").addClass("map-caronas-fixed").css("width", $(".container .area-pesquisa").width());
        } else {
          return $("#map-caronas").removeClass("map-caronas-fixed").removeAttr("style");
        }
      });
    };

    PesquisarCarona.prototype.eventWindowResize = function() {
      this.eventWindow();
      return $(window).resize((function(_this) {
        return function() {
          return _this.eventWindow();
        };
      })(this));
    };

    PesquisarCarona.prototype.eventWindow = function() {
      $(window).off("scroll");
      if ($(window).width() > 600) {
        return this.eventScrollMap();
      }
    };

    return PesquisarCarona;

  })();

  p = new PesquisarCarona();

}).call(this);

//# sourceMappingURL=pesquisar-carona.js.map
